name: Setup ESET in an LXC container
description: Must be ran on an Ubuntu or Debian runner

runs:
  using: composite  

  steps:    
    - name: Install dependencies
      shell: sh
      run: |
        sudo apt update
        #sudo apt install lxc lxc-templates dnsmasq liblxc-common iptables
        #sudo systemctl enable --now lxc-net

    - name: Install ESET in a container 
      if: true
      shell: sh
      run: |
        echo Create a container
        docker run --name tempdebian -d debian:bullseye sleep infinity

        echo Download the installer in the container 
        docker exec tempdebian wget https://download.eset.com/com/eset/apps/business/eea/linux/g2/latest/eeau_x86_64.bin

        echo Run the installer
        docker exec tempdebian chmod +x eeau_x86_64.bin
        docker exec tempdebian ./eeau_x86_64.bin -n -y
        docker exec tempdebian rm *.rpm
        docker exec tempdebian rm eeau_x86_64.bin
        docker exec tempdebian env ESET_DISABLE_WAP=1 dpkg -i $(ls | grep eea | grep .deb | head -n 1)

        echo Export container rootfs
        docker exec tempdebian rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        docker export tempdebian > rootfs.tar
        mkdir rootfs && tar -xf rootfs.tar -C rootfs
        docker rm -f tempdebian
      
    - name: Download ESET installer
      if: false
      shell: sh
      run: |
        wget https://download.eset.com/com/eset/apps/business/eea/linux/g2/latest/eeau_x86_64.bin

    - name: Build rootfs with Docker
      if: false
      shell: sh
      run: |
        echo Extract ESET installer
        chmod +x eeau_x86_64.bin
        ./eeau_x86_64.bin -n -y
        rm *.rpm
        rm eeau_x86_64.bin
        debfile=$(ls | grep eea | grep .deb | head -n 1)

        # Extract the content of the debfile
        mkdir -p eset-deb
        ar x $debfile
        tar xzf control.tar.gz -C eset-deb
        tar xzf data.tar.gz -C eset-deb

        echo Create a docker
        docker run --name tempdebian -d debian:bullseye sleep infinity

        echo Copy post install script into the container        
        docker cp eset-deb/postinst tempdebian:/tmp
        
        echo Copy ESET files into the container
        docker cp eset-deb/opt/* tempdebian:/opt
        docker cp eset-deb/var/* tempdebian:/var
        docker cp eset-deb/usr/* tempdebian:/usr

        echo Install ESET in the container
        docker exec tempdebian apt update && apt install -y libcurl4
        docker exec tempdebian env ESET_DISABLE_WAP=1 /tmp/postinst configure
        
        echo Export docker rootfs
        docker exec tempdebian rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        docker export tempdebian > rootfs.tar
        mkdir rootfs && tar -xf rootfs.tar -C rootfs
        docker rm -f tempdebian

    - name: Create Debian container
      if: false
      shell: sh
      env:
        pkgname: saphir-container-eset
        distro: debian
        release: bookworm
        arch: amd64
        variant: cloud
      run: |
        echo Create the container 
        sudo lxc-create -n $pkgname -t download -- --dist $distro --release $release --arch $arch --variant $variant
        sudo cat "/var/lib/lxc/$pkgname/config"

    - name: Create Debian chroot
      if: false 
      shell: sh
      run: |
        sudo apt install -y mmdebstrap wget debian-archive-keyring      
        sudo mmdebstrap --keyring /usr/share/keyrings/debian-archive-keyring.gpg --variant=minbase bullseye ./rootfs http://deb.debian.org/debian        

        echo Extract ESET installer
        chmod +x eeau_x86_64.bin
        ./eeau_x86_64.bin -n -y
        rm *.rpm
        rm eeau_x86_64.bin
        debfile=$(ls | grep eea | grep .deb | head -n 1)

        # Extract the content of the debfile
        mkdir -p eset-deb
        ar x $debfile
        tar xzf control.tar.gz -C eset-deb
        tar xzf data.tar.gz -C eset-deb

        echo Copy post install script into the container

        sudo mkdir -p ./rootfs/root
        sudo cp eset-deb/postinst ./rootfs/root

        # Copy ESET files into the container
        echo Copy ESET files into the container
        sudo cp -r eset-deb/opt/* ./rootfs/opt
        sudo cp -r eset-deb/var/* ./rootfs/var
        sudo cp -r eset-deb/usr/* ./rootfs/usr

        sudo chroot ./rootfs /bin/bash -c "apt update && apt install -y libcurl4"

        echo Execute ESET post install script
        sudo chroot ./rootfs /bin/bash -c "env ESET_DISABLE_WAP=1 /root/postinst configure"

    - name: Install ESET in the container
      if: false
      shell: sh 
      env:
        pkgname: saphir-container-eset
      run: |
        echo Extract ESET installer
        chmod +x eeau_x86_64.bin
        ./eeau_x86_64.bin -n -y
        rm *.rpm
        rm eeau_x86_64.bin
        debfile=$(ls | grep eea | grep .deb | head -n 1)

        # Extract the content of the debfile
        mkdir -p eset-deb
        ar x $debfile
        tar xzf control.tar.gz -C eset-deb
        tar xzf data.tar.gz -C eset-deb

        # Copy the post install script into the container
        echo Copy post install script into the container
        sudo cp eset-deb/postinst /var/lib/lxc/"$pkgname"/rootfs/root

        # Copy ESET files into the container
        echo Copy ESET files into the container
        sudo cp -r eset-deb/opt/* /var/lib/lxc/"$pkgname"/rootfs/opt
        sudo cp -r eset-deb/var/* /var/lib/lxc/"$pkgname"/rootfs/var
        sudo cp -r eset-deb/usr/* /var/lib/lxc/"$pkgname"/rootfs/usr

        # Setup the network
        #echo Start networking
        #sed -i '/^#lxc\.net/s/^#//' "/var/lib/lxc/$pkgname/config"
        #sudo rc-service dnsmasq.lxcbr0 start
        sysctl net.ipv4.ip_forward
        iptables -t nat -L -n

        # Start the container and install ESET
        echo Start LXC container
        #sudo service cgroups start
        sudo lxc-start -n "$pkgname"    

        sleep 1

        echo *** Check configuration
        sudo lxc-attach -n "$pkgname" -- ip link
        sudo lxc-attach -n "$pkgname" -- ip addr
        sudo lxc-attach -n "$pkgname" -- ip route
        sudo lxc-attach -n "$pkgname" -- cat /etc/resolv.conf

        echo *** Update APT
        sudo lxc-attach -n "$pkgname" -- apt update

        echo Install libcurl
        sudo lxc-attach -n "$pkgname" -- apt install -y libcurl4    

        echo Execute ESET post install script
        sudo lxc-attach -n "$pkgname" -- env ESET_DISABLE_WAP=1 /root/postinst configure

    - name: Optimize the container
      shell: sh 
      env:
        pkgname: saphir-container-eset
      run: |
        echo Clean the container to make it smaller
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/var/opt/eset/eea/updated
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/var/opt/eset/eea/lib/*.tar
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/doc
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/man
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/mime
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/info
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/vim
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/i18n
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/usr/share/locale
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/var/lib/apt/lists
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/lib/firmware
        sudo rm -rf /var/lib/lxc/"$pkgname"/rootfs/boot
        sudo lxc-attach -n "$pkgname" -- apt-get clean

    - name: Finalize installation
      shell: sh 
      env:
        pkgname: saphir-container-eset
      run: |
        # Stop the container
        echo Stop the container
        sudo lxc-stop -n "$pkgname"    

        # Disable networking
        echo Disable netorking
        sed -i 's/^lxc\.net/#&/' /var/lib/lxc/"$pkgname"/config

        # Add PSEC mount points
        echo Add mount points
        echo "" >> /var/lib/lxc/"$pkgname"/config
        echo "lxc.mount.entry = /mnt/storage mnt/storage none bind,optional,create=dir" >> /var/lib/lxc/"$pkgname"/config

        # Add XEN pv channels
        echo Add XEN PV channels
        echo "" >> /var/lib/lxc/"$pkgname"/config
        echo "lxc.mount.entry = /dev/hvc1 dev/hvc1 none bind,optional,create=file" >> /var/lib/lxc/"$pkgname"/config

        # Change the rootfs path
        sed -i '/^lxc\.rootfs\.path/d' /var/lib/lxc/"$pkgname"/config
        echo "lxc.rootfs.path = dir:/mnt/merged" >> /var/lib/lxc/"$pkgname"/config

    - name: Compress the container
      shell: sh
      env:
        pkgname: saphir-container-eset
      run: |
        tar cjf "/var/lib/lxc/$pkgname.tar.bz2" -C /var/lib/lxc .

    - name: Publish package
      uses: ./.github/actions/publish
      with:
        privkey: ${{ secrets.DEPLOY_KEY }}
        filepath: "/var/lib/lxc/$pkgname.tar.bz2"
        container: false
    