### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(themes)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "content/images/back.jpg"
        "content/images/back.png"
        "content/images/back_orig.png"
        "content/images/icn_antivirus.png"
        "content/images/icn_disk.png"
        "content/images/Logo.png"
        "content/shaders/blur.frag"
        "content/shaders/blur.frag.qsb"
        "content/shaders/colorize.frag"
        "content/shaders/colorize.frag.qsb"
        "content/shaders/gradient.frag"
        "content/shaders/gradient.frag.qsb"
        "content/shaders/invert_alpha.frag"
        "content/shaders/invert_alpha.frag.qsb"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Themesplugin
    QtQuickDesignerComponents)