### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Saphir)
add_subdirectory(themes)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "content/fonts/Inter-Italic-VariableFont_opsz_wght.ttf"
        "content/fonts/Inter-VariableFont_opsz_wght.ttf"
        "content/fonts/MaterialIcons-Regular.ttf"
        "content/fonts/MaterialIconsOutlined-Regular.otf"
        "content/images/3535287.jpg"
        "content/images/back.jpg"
        "content/images/back.png"
        "content/images/back_orig.png"
        "content/images/battery_android_2_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/battery_android_3_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/battery_android_4_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/battery_android_5_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/battery_android_6_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/battery_android_alert_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/battery_android_full_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"
        "content/images/icn_antivirus.png"
        "content/images/icn_disk.png"
        "content/images/Logo.png"
        "content/shaders/blur.frag"
        "content/shaders/blur.frag.qsb"
        "content/shaders/colorize.frag"
        "content/shaders/colorize.frag.qsb"
        "content/shaders/gradient.frag"
        "content/shaders/gradient.frag.qsb"
        "content/shaders/invert_alpha.frag"
        "content/shaders/invert_alpha.frag.qsb"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Saphirplugin
    Themesplugin
    QtQuickDesignerComponents)