### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "content/images/back.jpg"
        "content/images/back.png"
        "content/images/back_orig.png"
        "content/images/Logo.png"
        "content/shaders/combine_mask.frag"
        "content/shaders/combine_mask.frag.qsb"
        "content/shaders/mask.frag"
        "content/shaders/mask.frag.qsb"
        "content/shaders/rotatedgradient.frag"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_Effectsplugin
    Generated_Effects_Effect01plugin
    QtQuickDesignerComponents)