#!/bin/sh

# Script to be run after package is installed

WAPD_SET_SYSCTL=1
WAPD_SET_UDEV=1

SYSTEMD_CAT="$(which systemd-cat 2>/dev/null || true)"
print_error() {
	errorstr="ESET Endpoint Antivirus error: $1"
	echo "$errorstr" 1>&2
	if [ -n "$SYSTEMD_CAT" ]; then
		printf "%s" "$errorstr" | $SYSTEMD_CAT -t "eea" -p err
	fi
}

# import config engine configuration from old product
import_configuration() {
	# import only if we have exported xml from old product
	if [ -f '/var/opt/eset/eea/confd/exported.xml' ]; then
		# we don't want to leave old settings.json, all information is
		# in exported xml
		rm -f '/var/opt/eset/eea/confd/settings.json'
		confd_ug='eset-eea-confd:eset-eea-daemons'
		sudo -u ${confd_ug%:*} -- '/opt/eset/eea/lib/cfg-upgrade' --import-xml '/var/opt/eset/eea/confd/exported.xml'
		rm -f '/var/opt/eset/eea/confd/exported.xml'
	fi
}


if [ "$1" = "configure" ] || [ "$1" = "1" ] || [ "$1" = "2" ]; then
	# first install and upgrade (deb only)
	# yum: run for "1" (install) and "2" (upgrade)
	# check if users have been already created

	# create users and groups
	for g in eset-eea-agents eset-eea-daemons; do
		groupadd -r -f $g
	done

	for ug in eset-eea-confd:eset-eea-daemons eset-eea-updated:eset-eea-daemons eset-eea-licensed:eset-eea-daemons eset-eea-scand:eset-eea-daemons eset-eea-econnd:eset-eea-daemons eset-eea-sched:eset-eea-agents eset-eea-logd:eset-eea-daemons eset-eea-vapmd:eset-eea-daemons eset-eea-wapd:eset-eea-daemons; do
		if ! id "${ug%:*}" > /dev/null 2>&1; then
			useradd -d '/opt/eset/eea' -M -N -r -s /sbin/nologin -g "${ug#*:}" "${ug%:*}"
		fi
	done
fi

#################################### Upgrade & Install ####################################
# change directory permissions
logd_ug='eset-eea-logd:eset-eea-daemons'
chown ${logd_ug%:*} '/var/log/eset/eea'
chmod 700 '/var/log/eset/eea'


chgrp 'eset-eea-daemons' '/var/opt/eset/eea' '/var/opt/eset/eea/cache' '/var/opt/eset/eea/cache/data' '/var/opt/eset/eea/installer' '/var/opt/eset/eea/vapm' '/var/opt/eset/eea/lib' '/var/opt/eset/eea/modules_notice' '/var/opt/eset/eea/updated' '/var/opt/eset/eea/updated/modules' '/var/opt/eset/eea/dumps'
chmod 775 '/var/opt/eset/eea' '/var/opt/eset/eea/cache' '/var/opt/eset/eea/cache/data' '/var/opt/eset/eea/installer' '/var/opt/eset/eea/vapm' '/var/opt/eset/eea/lib' '/var/opt/eset/eea/modules_notice' '/var/opt/eset/eea/updated' '/var/opt/eset/eea/updated/modules' '/var/opt/eset/eea/dumps'

mkdir -p '/var/opt/eset/eea/cache/data/Logs'
mkdir -p '/var/opt/eset/eea/cache/data/Diagnostics'

chgrp 'eset-eea-daemons' '/var/opt/eset/eea/cache/data/Logs' '/var/opt/eset/eea/cache/data/Diagnostics'

scand_ug='eset-eea-scand:eset-eea-daemons'
for dir in /var/opt/eset/eea/cache /var/opt/eset/eea/cache/data '/var/opt/eset/eea/cache/data/Logs' '/var/opt/eset/eea/cache/data/Diagnostics'; do
	chmod 770 "$dir"
	chmod 1770 "$dir"
	chown ${scand_ug%:*} "$dir"
done

# extract modules from tar
tar -xf /var/opt/eset/eea/lib/modules_eea.tar -C /var/opt/eset/eea/updated/modules
# compile modules
/opt/eset/eea/bin/upd --compile-nups
upd_return_code=$?
if [ $upd_return_code -ne 0 ] && [ $upd_return_code -ne 10 ]; then
	print_error 'Module compilation failed.'
fi

# set correct user to compiled modules and updater data dir
updated_ug='eset-eea-updated:eset-eea-daemons'
chown -R ${updated_ug} /var/opt/eset/eea/lib /var/opt/eset/eea/updated/modules

if [ "$1" = "2" ]; then
	# rpm upgrade only
	import_configuration
fi

if [ "$1" = "configure" ] && [ -n "$2" ]; then
	# deb upgrade only
	import_configuration
fi

# disable WAP integration based on env variable passed to installer
wap_disabler_path="/opt/eset/eea/etc/WAP_DISABLED"
if [ -n "$ESET_DISABLE_WAP" ]; then
	echo "1" > "$wap_disabler_path"
fi

if [ $WAPD_SET_SYSCTL -eq 1 ] && [ -z "$ESET_DISABLE_WAP" ]; then
	'/opt/eset/eea/lib/install_scripts/eset_eea_sysctl.sh' enable
fi

if [ $WAPD_SET_UDEV -eq 1 ] && [ -z "$ESET_DISABLE_WAP" ]; then
	'/opt/eset/eea/lib/install_scripts/eset_eea_udev.sh' enable
fi

# enable SHA256 integration based on env variable passed to installer
sha256_enabler_path="/opt/eset/eea/etc/SHA256_ENABLED"
if [ -n "$ESET_ENABLE_SHA256" ]; then
	echo "1" > "$sha256_enabler_path"
fi

# register and start service
'/opt/eset/eea/lib/install_scripts/register_service.sh'

# add current eula info into CE path AcceptedEulas
# esmc may have already modified this by policy, in that case it is locked, so
# ignore error here and leave esmc to manage this setting
'/opt/eset/eea/lib/cfg' --eula-tag "EULA-PRODUCT-LG" --eula-version "3537.0.0" > /dev/null || true