name: Publish to official repository

inputs:
  privkey:
    description: Base64 encoded private key
    required: true
  filepath:
    description: The full path of the file to upload
    required: true
  container:
    description: Is this action running into an Alpine container
    required: false
    default: true

runs:
  using: composite  

  steps:    
    - name: Install missing packages (Alpine)
      if: ${{ inputs.container == 'true' }}
      shell: sh
      run: |
        apk update || true
        apk add rsync openssh-client-common openssh-client

    - name: Install missing packages (Ubuntu)
      if: ${{ inputs.container == 'false' }}
      shell: sh
      run: |
        sudo apt update 
        sudo apt install rsync openssh-client

    - name: Restore SSH key
      shell: sh
      run: |
        mkdir -p ssh
        chmod 700 ssh
        echo "${{ inputs.privkey }}" | base64 -d > ssh/id_rsa
        chmod 600 ssh/id_rsa

    - name: Add server to known_hosts
      shell: sh
      run: |
        ssh-keyscan -4 -p 222 alefbet.net >> ssh/known_hosts

    - name: Copy files to server
      shell: sh
      run: |
        rsync -av -e 'ssh -p 222 -4 -i ssh/id_rsa -o StrictHostKeyChecking=no' ${{ inputs.filepath }} github-saphir@alefbet.net:/var/www/www.alefbet.net/github/saphir/x86_64/

    - name: Recreate and sign APK index 
      shell: sh
      run: |
        ssh -p 222 -4 -i ssh/id_rsa -o StrictHostKeyChecking=no github-saphir@alefbet.net <<'EOF'
          set -e
          docker run --rm -v /var/www/www.alefbet.net/github/saphir/x86_64:/mnt/apk   -v /home/github-saphir:/mnt/keys   alpine:3.20 sh -c "
            apk add --no-cache alpine-sdk
            cp /mnt/keys/saphir.rsa.pub /etc/apk/keys
            cd /mnt/apk
            echo 'Building APK index...'
            apk index -d Saphir -o APKINDEX.tar.gz *.apk
            echo 'Signing APK index...'
            abuild-sign -k /mnt/keys/saphir.rsa -p /mnt/keys/saphir.rsa.pub APKINDEX.tar.gz 
            cd /mnt/apk
            chown $(id -u):$(id -g) *
            chmod 644 *
          "          
        EOF
